---
# This is a basic workflow to help you get started with Actionss

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test-build"
  test-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3

      - name: Installing global dependencies
        run: |
          pip3 install dump-env docker-image-size-limit
          dump-env -t config/.env.template -p 'SECRET_' > config/.env
          docker info && docker-compose --version && git --version
          echo "${{ secrets.GITHUB_TOKEN }}"

      - name: Login docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u iamilyagurin --password-stdin

      - name: Checking config
        run: docker-compose -f docker-compose.yml -f docker/docker-compose.prod.yml config --quiet

      - name: Pull docker image
        run: |
          docker pull "docker.pkg.github.com/iamilyagurin/sls/sls:dev" || true
          docker tag "docker.pkg.github.com/iamilyagurin/sls/sls:dev" "sls:dev" || true

      - name: Build docker image
        run: docker-compose build

      - name: Run ci.sh
        run: docker-compose run --rm web sh ./docker/ci.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true

      - name: Push docker image
        run: |
          docker tag "sls:dev" "docker.pkg.github.com/iamilyagurin/sls/sls:dev"
          docker push "docker.pkg.github.com/iamilyagurin/sls/sls:dev"
